version: '3.6'
services:
  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - ./volumes/data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - aaw
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  gql:
    image: hasura/graphql-engine:v2.16.0
    # image: hasura/graphql-engine:v2.16.0.cli-migrations-v3
    ports:
      - 8888:8080
    depends_on:
      - db
    restart: always
    networks:
      - aaw
    # volumes:
    #   - ./hasura/metadata:/hasura-metadata
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey

  adminer:
    image: adminer:latest
    restart: always
    networks:
      - aaw
    environment: 
      ADMINER_DESIGN: dracula
      ADMINER_DEFAULT_SERVER: db
    depends_on: 
      - db
    ports:
      - 19999:8080

networks:
  aaw:
